name: akstestgh
type: online
infrastructure: azureml:devplatv2aks
auth_mode: Key
traffic:
    etblue: 80
    etgreen: 20
deployments:
    etblue:   
        model: azureml:my-model-1:1
        code_configuration:
            code:
                directory: code
            scoring_script: main.py
        environment:
            name: sklearn-aks-env
            version: 1
            path: .
            conda_file: environment/conda.yml
        scale_settings:
            scale_type: manual
            instance_count: 1
        request_settings:
            request_timeout_ms: 3000
            max_concurrent_requests_per_instance: 1
            max_queue_wait_ms: 3000
        resource_requirements:
            cpu: 1.5
            # memory_in_gb: 1.0
    etgreen:   
        model: azureml:my-model-2:1
        code_configuration:
            code:
                directory: code
            scoring_script: main.py
        environment:
            name: sklearn-aks-env
            version: 1
            path: .
            conda_file: environment/conda.yml
        scale_settings:
            scale_type: manual
            instance_count: 1
        request_settings:
            request_timeout_ms: 3000
            max_concurrent_requests_per_instance: 1
            max_queue_wait_ms: 3000
        resource_requirements:
            cpu: 1.5
            # memory_in_gb: 1.0
