name: Build and run CLI

on: 
  push:
    branches:
      - main
    paths-ignore:
    - 'website/**'
jobs:
  dev-setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk2-src
    env:
      AZURE_EXTENSION_DIR: ${{ github.workspace }}/sdk2-src/src/cli/src 
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - run: sudo npm install -g autorest
    - run: python scripts/dev_setup.py -s
    - run: python scripts/dev_setup.py -c
    - run: echo $GITHUB_WORKSPACE
 #   - run: pip install -e ./src/cli/src/machinelearningservices
 #   - run: echo $AZURE_EXTENSION_DIR
    - run: az extension list
    - run: az ml -h
    - run: az ml job -h
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: cli
        path: sdk2-src/src/cli/src
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_TOKEN}}
    - run: az ml environment create --workspace-name devplatv2 --resource-group demorg --subscription 92c76a2f-0e1c-4216-b65e-abf7a3f34c1e --file examples/fastai-env.yml
      working-directory: .
      continue-on-error: true
    - run: az ml job create --workspace-name devplatv2 --resource-group demorg --subscription 92c76a2f-0e1c-4216-b65e-abf7a3f34c1e --file examples/commandjob.yml
      working-directory: .
      continue-on-error: true
    - run: az ml job create --workspace-name devplatv2 --resource-group demorg --subscription 92c76a2f-0e1c-4216-b65e-abf7a3f34c1e --file examples/fastai_mnist_job.yml
      working-directory: .
      continue-on-error: true
    - run: az ml job create --workspace-name devplatv2 --resource-group demorg --subscription 92c76a2f-0e1c-4216-b65e-abf7a3f34c1e --file samples/yaml/code_job.yml
      continue-on-error: true
