name: cli-e2etest

on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
jobs:
  dev-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - run: |
        az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.6-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
    - run: az ml -h
    - run: az ml job -h
    - run: az ml data -h
    - run: az ml datastore -h
    - run: az ml model -h
    - run: az ml environment -h
    - run: az ml endpoint -h
    - run: az ml compute -h
    - run: az ml workspace -h
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_TOKEN}}
    - run: |
          az config set defaults.workspace=e2edemos
          az config set defaults.group=demorg
          az account set -s 92c76a2f-0e1c-4216-b65e-abf7a3f34c1e
    - run: |
          az ml environment create --file examples/train/fastai/pets-resnet34/fastai_vision_env.yml
    - run: |
          az ml environment create --file examples/train/r/r_minimal_env.yml
    - run: |
          az ml environment create --file examples/train/r/r_cran_env.yml
    - run: |
          az ml environment create --file examples/iris/xgboost-env.yml
    - run: |
          az ml environment create --file examples/train/fastai/mnist-resnet18/fastai_env.yml
    - run: |
          az ml environment create --file examples/environments/tensorflow/tf_env.yml
    - run: |
          az ml data create --file examples/iris/iris-data.yml
    - run: |
          az ml job create --file examples/iris/iris-job.yml --name iris_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
    - run: |
          az ml job create --file examples/train/basic-command-job/pip_freeze_job.yml  --name pipfreeze_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
    - run: |
          az ml job create --file examples/train/basic-command-job/command_job.yml  --name commandtest_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
    - run: |
          az ml job create --file examples/train/r/r_job.yml  --name rtest_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
    - run: |
          az ml job create --file examples/train/fastai/mnist-resnet18/fastai_mnist_job.yml --name fastai_mnist_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
    - run: |
          az ml job create --file examples/sweep/sweepjob.yml --name sweeptest_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
    - run: |
          az ml model create --file sdk2-src/samples/yaml/model.azml-Model.yaml
    - run: |
          az ml endpoint create --file examples/deploy/sklearn/basicaksendpoint.yml
      continue-on-error: true
