name: sphinx-docs
on:
  push:
    branches:
      - main
    paths: 
      - docs/**
      - sdk2-src/**
      - .github/workflows/sphinx-docs.yml
jobs:
  build:
    name: deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
        with:
          working-directory: docs
      - run: make html
        with: 
          working-directory: docs
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      - run: git config --global user.email "azureml@microsoft.com"
      - run: git config --global user.name "Azure ML"
      - run: git checkout -b docs
      - run: git add -f docs
      - run: git commit -m "adding built sphinx docs"
      - run: git push -uf origin docs
